# Your project's server will run on proxy
PROXY: "https://pype.dev"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "themes/primer/assets/dist"
  # Path to source folder
  src: "themes/primer/assets/src"
  # Paths to fonts
  fonts:
    - "themes/primer/assets/src/fonts/font-awesome/**/*"
  # Paths to images
  images:
    - "themes/primer/assets/src/img/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "vendor/scrivo/highlight.php/styles"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    - "vendor/bower/jquery/dist/jquery.js"
    - "themes/primer/assets/src/js/jquery.sticky.js"
    - "themes/primer/assets/src/js/lightbox.js"
    - "themes/primer/assets/src/js/jquery.cookiesdirective.js"
    - "themes/primer/assets/src/js/custom.js"
